app_name: "Ruby on Rails Tutorial Sample App"
navbar:
  brand: "Sample App"
  home: "Home"
  help: "Help"
  contact: "Contact"
static_pages:
  home:
    title: "Home"
    header: "Sample App"
    description: "This is the home page for the"
    tutorial_link_text: "Ruby on Rails Tutorial"
    tutorial_link_url: "http://www.railstutorial.org/"
    sample_app_text: "sample application."
  help:
    title: "Help"
    header: "Help"
    description_1: "Get help on the Ruby on Rails Tutorial at the"
    help_link_text: "Rails Tutorial help page"
    help_link_url: "http://www.railstutorial.org/help"
    description_2: "To get help on this sample app, see the"
    book_link_text: "Ruby on Rails Tutorial"
    book_link_url: "http://www.railstutorial.org/book"
    book_link_em: true
  contact:
    title: "Contact"
    header: "Contact"
    hello: "Hello, YourName"
